version: '3.2'

services:
  web:
    container_name: podcasts_nginx
    image: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - php
      - database
  #      - redis

  php: &app-podcasts-service
    container_name: podcasts_php
    build:
      args:
        user: podcast
        uid: 1000
      context: .docker/php
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./src/:/var/www/html

#  queue:
#    <<: *app-podcasts-service
#    container_name: podcasts_queue
#    restart: always
#    command: php /var/www/html/artisan queue:work

  scheduler:
    <<: *app-podcasts-service
    container_name: podcasts_scheduler
    restart: always
    command: /scheduler/scheduler.sh

  database:
    container_name: podcasts_database
    image: postgres:13.2
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - postgres-database-podcasts:/var/lib/postgresql/data

#  clickhouse:
#    container_name: podcasts_clickhouse
#    image: yandex/clickhouse-server:latest
#    ports:
#      - '8123:8123'
#      - '9000:9000'
#    volumes:
#      - clickhouse-database-podcasts:/var/lib/clickhouse

#  redis:
#    container_name: podcasts_redis
#    build: .docker/redis
#    restart: always
#    ports:
#      - '6379:6379'
#    volumes:
#      - redis-podcasts:/data:rw

volumes:
  postgres-database-podcasts:
    driver: local
#  clickhouse-database-podcasts:
#    driver: local
#  redis-podcasts:
#    driver: local
